name: Android CI

on:
  push:
    branches: [ "slider" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build gradle project
      run: ./gradlew build

    - name: Build release apk
      run: ./gradlew assemble
    
    - name: Save artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk