name: Android CI

on:
  push:
    branches: [ "slider" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: set up JDK
      uses: actions/setup-java@v4.1.0
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build gradle project
      run: ./gradlew build

    - name: Build debug apk
      run: ./gradlew assembleDebug

    - name: Build release apk
      run: ./gradlew assembleRelease
    
    - name: Save debug apk
      uses: actions/upload-artifact@v4.3.1
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk
    
    - name: Save release apk
      uses: actions/upload-artifact@v4.3.1
      with:
        name: app-release
        path: app/build/outputs/apk/release/*.apk
